keys:
  - &nikita age17xyy5ghfcgmx9zqgsy30a77cnzfp2dc9u2pnyrywkt37l6npnemsnx823c
  - &server_nihonzaru age1frgcsf9h7jwyucs6p8da32479r3g6ga3xqsx03qx2qfn5unulggqayrg2r
creation_rules:
  - path_regex: hosts/pc/[^/]+\.yaml$
    key_groups:
    - age:
      - *nikita
  - path_regex: hosts/nihonzaru/[^/]+\.yaml$
    key_groups:
    - age:
      - *nikita
      - *server_nihonzaru
