# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}:

{
  imports = [ (modulesPath + "/installer/scan/not-detected.nix") ];

  boot.initrd.availableKernelModules = [
    "xhci_pci"
    "ahci"
    "nvme"
    "usbhid"
    "usb_storage"
    "sd_mod"
  ];
  boot.kernelPackages = pkgs.linuxPackages_6_12;
  boot.initrd.kernelModules = [ "dm-snapshot" ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.blacklistedKernelModules = [ ];
  boot.extraModulePackages = [ ];
  boot.supportedFilesystems = [ "zfs" ];
  boot.zfs.forceImportRoot = false;
  boot.zfs.extraPools = [ "zpool" ];
  boot.zfs.package = pkgs.zfs_unstable;

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/5d09542d-d9b8-457d-9b24-51e146310c73";
    fsType = "ext4";
  };

  boot.initrd.luks.devices = {
    crypted = {
      # $ blkid /dev/nvme0n1p2
      # <outputs uuid>
      device = "/dev/disk/by-uuid/de23d992-6e1c-44a2-bd9f-7d14e888baef";
      preLVM = true;
    };
    crypted-data = {
      device = "/dev/disk/by-uuid/2838ccd2-89c6-4506-a85b-4ecc75f723e7";
      preLVM = true;
    };
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/A576-AFA9";
    fsType = "vfat";
    options = [
      "fmask=0022"
      "dmask=0022"
    ];
  };

  fileSystems."/mnt/steam-library" = {
    device = "/dev/disk/by-uuid/4be2e5ac-b248-4210-b0c2-f4daec2f2adf";
    fsType = "ext4";
  };

  #fileSystems."/mnt/data" = {
  #  device = "zpool";
  #  fsType = "zfs";
  #  options = [ "nofail" ];
  #};

  #fileSystems."/mnt/data/videos" = {
  #  device = "zpool/videos";
  #  fsType = "zfs";
  #  options = [ "nofail" ];
  #};

  # zpool settings used[1]:
  # ashift=12 xattr=sa compression=lz4 atime=off
  #
  # Was created in mirror mode for 2x10Tb disks
  #
  # [1]: https://jrs-s.net/2018/08/17/zfs-tuning-cheat-sheet/

  swapDevices = [ { device = "/dev/disk/by-uuid/b3c18ad6-20ae-4c37-89f1-46a6bc8fd635"; } ];

  hardware.bluetooth.enable = true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  powerManagement.cpuFreqGovernor = lib.mkDefault "powersave";
}
