{
  inputs,
  config,
  lib,
  pkgs,
  ...
}:
{
  imports = [
    inputs.self.nixosModules.roles.minimal

    inputs.self.nixosModules.profiles.server.acme
    inputs.self.nixosModules.profiles.server.nginx

    inputs.self.nixosModules.profiles.server.vaultwarden
    inputs.self.nixosModules.profiles.server.website
    inputs.self.nixosModules.profiles.server.xray

    ./hardware-configuration.nix
    ./mounts.nix
    ./networking.nix # generated at runtime by nixos-infect
  ];

  programs.git.enable = true;

  boot.tmp.cleanOnBoot = true;
  zramSwap.enable = true;

  users.users.root.openssh.authorizedKeys.keys = [
    "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIG8UNqMGTX8xDs9BZSc/nuRh6NHsgovyeFMh2+OQl63Y"
  ];

  #TODO: this was autgenerated by nixos-infect, check if this could be removed
  networking.domain = "";

  system.stateVersion = "24.05";
}
