{
  inputs,
  config,
  lib,
  pkgs,
  ...
}:
{
  imports = [
    inputs.self.nixosModules.roles.minimal

    inputs.self.nixosModules.profiles.server.acme
    inputs.self.nixosModules.profiles.server.nginx

    inputs.self.nixosModules.profiles.server.vaultwarden
    ../../hosts/nihonzaru/modules/vim.nix
    ../../hosts/nihonzaru/modules/xray.nix
    ../../hosts/nihonzaru/modules/my-xray.nix

    ./hardware-configuration.nix
    ./mounts.nix
    ./networking.nix # generated at runtime by nixos-infect
  ];

  sops.defaultSopsFile = ../../hosts/nihonzaru/secrets.yaml;

  programs.git.enable = true;

  boot.tmp.cleanOnBoot = true;
  zramSwap.enable = true;

  users.users.root.openssh.authorizedKeys.keys = [
    "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIG8UNqMGTX8xDs9BZSc/nuRh6NHsgovyeFMh2+OQl63Y"
  ];

  #TODO: this was autgenerated by nixos-infect, check if this could be removed
  networking.domain = "";

  #TODO: how does this work?
  # If not specified for this host, build fails with:
  #        error: Unknown kernel: linux
  # Seems to be not required on other machines...
  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";

  system.stateVersion = "24.05";
}
