{
  inputs,
  config,
  lib,
  pkgs,
  ...
}:
{
  #imports = [
  #  inputs.self.nixosModules.roles.minimal

  #  ./hardware-configuration.nix
  #  ./mounts.nix
  #];

  imports = [

    inputs.sops-nix.nixosModules.sops
    ../../hosts/nihonzaru/hardware-configuration.nix
    ../../hosts/nihonzaru/networking.nix # generated at runtime by nixos-infect

    ../../hosts/nihonzaru/modules/nginx
    ../../hosts/nihonzaru/modules/acme.nix
    ../../hosts/nihonzaru/modules/vaultwarden.nix
    ../../hosts/nihonzaru/modules/vim.nix
    ../../hosts/nihonzaru/modules/xray.nix
    ../../hosts/nihonzaru/modules/my-xray.nix
  ];

  sops.defaultSopsFile = ../../hosts/nihonzaru/secrets.yaml;

  programs.git.enable = true;

  boot.tmp.cleanOnBoot = true;
  zramSwap.enable = true;

  nix.settings.experimental-features = "nix-command flakes";

  services.openssh = {
    enable = true;
    settings = {
      PasswordAuthentication = false;
    };
  };

  users.users.root.openssh.authorizedKeys.keys = [
    "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIG8UNqMGTX8xDs9BZSc/nuRh6NHsgovyeFMh2+OQl63Y"
  ];

  #TODO: this was autgenerated by nixos-infect, check if this could be removed
  networking.domain = "";

  #TODO: how does this work?
  # If not specified for this host, build fails with:
  #        error: Unknown kernel: linux
  # Seems to be not required on other machines...
  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";

  system.stateVersion = "24.05";
}
